/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Examen_PrograII;

import javax.swing.JComboBox;

/**
 *
 * @author jenniferbueso
 */
public class AgregarBarco extends javax.swing.JFrame {

    /**
     * Creates new form AgregarBarco
     */
    public AgregarBarco() {
        initComponents();
        
        PesqueroPanel.setVisible(false);
        PasajeroPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JLabel();
        PasajeroPanel = new javax.swing.JPanel();
        PrecioBoletosField = new javax.swing.JTextField();
        LimitePasajerosField = new javax.swing.JTextField();
        NombrePasajeroField = new javax.swing.JTextField();
        Moneda = new javax.swing.JLabel();
        FondoPesquero1 = new javax.swing.JLabel();
        PesqueroPanel = new javax.swing.JPanel();
        NombrePesqueroField = new javax.swing.JTextField();
        TipoCargaBox = new javax.swing.JComboBox<>();
        FondoPesquero = new javax.swing.JLabel();
        TiposBarcoBox = new javax.swing.JComboBox<>();
        BotonRegresar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 160, 40));

        PasajeroPanel.setBackground(new java.awt.Color(228, 208, 208));
        PasajeroPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrecioBoletosField.setBackground(new java.awt.Color(213, 180, 180));
        PrecioBoletosField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        PrecioBoletosField.setForeground(new java.awt.Color(113, 91, 91));
        PrecioBoletosField.setBorder(null);
        PrecioBoletosField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioBoletosFieldKeyTyped(evt);
            }
        });
        PasajeroPanel.add(PrecioBoletosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 132, 190, 30));

        LimitePasajerosField.setBackground(new java.awt.Color(213, 180, 180));
        LimitePasajerosField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        LimitePasajerosField.setForeground(new java.awt.Color(113, 91, 91));
        LimitePasajerosField.setBorder(null);
        LimitePasajerosField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LimitePasajerosFieldKeyTyped(evt);
            }
        });
        PasajeroPanel.add(LimitePasajerosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 49, 220, 30));

        NombrePasajeroField.setBackground(new java.awt.Color(213, 180, 180));
        NombrePasajeroField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        NombrePasajeroField.setForeground(new java.awt.Color(113, 91, 91));
        NombrePasajeroField.setBorder(null);
        PasajeroPanel.add(NombrePasajeroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 49, 220, 30));

        Moneda.setBackground(new java.awt.Color(213, 180, 180));
        Moneda.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        Moneda.setForeground(new java.awt.Color(113, 91, 91));
        Moneda.setText("$. ");
        PasajeroPanel.add(Moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 132, 20, 30));

        FondoPesquero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/PasajeroPanel.png"))); // NOI18N
        PasajeroPanel.add(FondoPesquero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(PasajeroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 600, 180));

        PesqueroPanel.setBackground(new java.awt.Color(228, 208, 208));
        PesqueroPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombrePesqueroField.setBackground(new java.awt.Color(213, 180, 180));
        NombrePesqueroField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        NombrePesqueroField.setForeground(new java.awt.Color(113, 91, 91));
        NombrePesqueroField.setBorder(null);
        PesqueroPanel.add(NombrePesqueroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 30));

        TipoCargaBox.setBackground(new java.awt.Color(255, 255, 255));
        TipoCargaBox.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TipoCargaBox.setForeground(new java.awt.Color(113, 91, 91));
        TipoCargaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Pez", "Camarón", "Langosta" }));
        PesqueroPanel.add(TipoCargaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 91, 180, 30));

        FondoPesquero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/PesqueroPanel.png"))); // NOI18N
        PesqueroPanel.add(FondoPesquero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(PesqueroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 600, 180));

        TiposBarcoBox.setBackground(new java.awt.Color(255, 255, 255));
        TiposBarcoBox.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TiposBarcoBox.setForeground(new java.awt.Color(113, 91, 91));
        TiposBarcoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Pesquero", "Pasajero" }));
        TiposBarcoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiposBarcoBoxActionPerformed(evt);
            }
        });
        jPanel1.add(TiposBarcoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 160, 30));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 50, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/AgregarBarco.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarMouseClicked
        String tipoBarco = TiposBarcoBox.getSelectedItem().toString();
        String nombre = "";
        
        if (tipoBarco.equals("Pesquero")) {
            nombre = NombrePesqueroField.getText().toUpperCase();
            Main_Muelle.muelle.setTipoCarga(TipoCargaBox.getSelectedItem().toString().toUpperCase());
        } else if (tipoBarco.equals("Pasajero")) {
            nombre = NombrePasajeroField.getText().toUpperCase();
            int limitePasajeros = Integer.parseInt(LimitePasajerosField.getText());
            double precioBoleto = Double.parseDouble(PrecioBoletosField.getText());
            Main_Muelle.muelle.setLimitePasajeros(limitePasajeros);
            Main_Muelle.muelle.setPrecioBoleto(precioBoleto);
        }
        
        Main_Muelle.muelle.setNombreAgregar(nombre);
        Main_Muelle.muelle.agregarBarco(tipoBarco);
        
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BotonAgregarMouseClicked

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void TiposBarcoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiposBarcoBoxActionPerformed
        String mostrar = TiposBarcoBox.getSelectedItem().toString();
        
        if (mostrar.equals("Pesquero")) {
            PesqueroPanel.setVisible(true);
            PasajeroPanel.setVisible(false);
            PrecioBoletosField.setText(null);
            LimitePasajerosField.setText(null);
            NombrePasajeroField.setText(null);
        } else if (mostrar.equals("Pasajero")) {
            PesqueroPanel.setVisible(false);
            PasajeroPanel.setVisible(true);
            NombrePesqueroField.setText(null);
            TipoCargaBox.setSelectedIndex(1);
        } else if (mostrar.equals(" ")) {
            PesqueroPanel.setVisible(false);
            PasajeroPanel.setVisible(false);
            PrecioBoletosField.setText(null);
            LimitePasajerosField.setText(null);
            NombrePasajeroField.setText(null);
            NombrePesqueroField.setText(null);
            TipoCargaBox.setSelectedIndex(1);
        }
    }//GEN-LAST:event_TiposBarcoBoxActionPerformed

    private void PrecioBoletosFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioBoletosFieldKeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            evt.consume();
        }
    }//GEN-LAST:event_PrecioBoletosFieldKeyTyped

    private void LimitePasajerosFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LimitePasajerosFieldKeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            evt.consume();
        }
    }//GEN-LAST:event_LimitePasajerosFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarBarco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoPesquero;
    private javax.swing.JLabel FondoPesquero1;
    private javax.swing.JTextField LimitePasajerosField;
    private javax.swing.JLabel Moneda;
    private javax.swing.JTextField NombrePasajeroField;
    private javax.swing.JTextField NombrePesqueroField;
    private javax.swing.JPanel PasajeroPanel;
    private javax.swing.JPanel PesqueroPanel;
    private javax.swing.JTextField PrecioBoletosField;
    private javax.swing.JComboBox<String> TipoCargaBox;
    private javax.swing.JComboBox<String> TiposBarcoBox;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
