/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Examen_PrograII;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonBuscarPorFecha = new javax.swing.JLabel();
        BotonVaciarBarco = new javax.swing.JLabel();
        BotonAgregarElemento = new javax.swing.JLabel();
        BotonAgregarBarco = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBuscarPorFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscarPorFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarPorFechaMouseClicked(evt);
            }
        });
        jPanel1.add(BotonBuscarPorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 160, 120));

        BotonVaciarBarco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVaciarBarco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVaciarBarcoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonVaciarBarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 150, 120));

        BotonAgregarElemento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarElemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarElementoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 160, 120));

        BotonAgregarBarco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarBarco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarBarcoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarBarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, 120));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/MenuPrincipal.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarBarcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarBarcoMouseClicked
        AgregarBarco agregarBarco = new AgregarBarco();
        agregarBarco.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarBarcoMouseClicked

    private void BotonAgregarElementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarElementoMouseClicked
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del barco: ", "Agregar Elemento", JOptionPane.OK_CANCEL_OPTION);
        nombre = nombre.toUpperCase();
        
        if (nombre.isBlank() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete el campo de Nombre.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!nombre.isBlank() || !nombre.isEmpty()) {
            Main_Muelle.muelle.agregarElemento(nombre);
        }
    }//GEN-LAST:event_BotonAgregarElementoMouseClicked

    private void BotonVaciarBarcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVaciarBarcoMouseClicked
        VaciarBarco vaciarBarco = new VaciarBarco();
        vaciarBarco.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonVaciarBarcoMouseClicked

    private void BotonBuscarPorFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarPorFechaMouseClicked
        BuscarPorFecha buscarPorFecha = new BuscarPorFecha();
        buscarPorFecha.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonBuscarPorFechaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregarBarco;
    private javax.swing.JLabel BotonAgregarElemento;
    private javax.swing.JLabel BotonBuscarPorFecha;
    private javax.swing.JLabel BotonVaciarBarco;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
