/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Examen_PrograII;

import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class VaciarBarco extends javax.swing.JFrame {

    /**
     * Creates new form VaciarBarco
     */
    public VaciarBarco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DatosBarcoArea = new javax.swing.JTextArea();
        NombreBarcoField = new javax.swing.JTextField();
        TotalGeneradoLabel = new javax.swing.JLabel();
        TipoBarcoLabel = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 160, 40));

        jScrollPane1.setBorder(null);

        DatosBarcoArea.setEditable(false);
        DatosBarcoArea.setBackground(new java.awt.Color(228, 208, 208));
        DatosBarcoArea.setColumns(20);
        DatosBarcoArea.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        DatosBarcoArea.setForeground(new java.awt.Color(113, 91, 91));
        DatosBarcoArea.setRows(5);
        DatosBarcoArea.setBorder(null);
        jScrollPane1.setViewportView(DatosBarcoArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 330, 150));

        NombreBarcoField.setBackground(new java.awt.Color(213, 180, 180));
        NombreBarcoField.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        NombreBarcoField.setForeground(new java.awt.Color(113, 91, 91));
        NombreBarcoField.setBorder(null);
        jPanel1.add(NombreBarcoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 174, 170, 30));

        TotalGeneradoLabel.setBackground(new java.awt.Color(213, 180, 180));
        TotalGeneradoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TotalGeneradoLabel.setForeground(new java.awt.Color(113, 91, 91));
        TotalGeneradoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(TotalGeneradoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 434, 170, 30));

        TipoBarcoLabel.setBackground(new java.awt.Color(213, 180, 180));
        TipoBarcoLabel.setFont(new java.awt.Font("Avenir Next Condensed", 1, 18)); // NOI18N
        TipoBarcoLabel.setForeground(new java.awt.Color(113, 91, 91));
        TipoBarcoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(TipoBarcoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 347, 170, 30));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 40, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/VaciarBarco.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarMouseClicked
        String nombre = NombreBarcoField.getText().toUpperCase();
         
        if (nombre.isBlank() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete el campo de Nombre.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!nombre.isBlank() || !nombre.isEmpty()) {
            Main_Muelle.muelle.buscarBarco(nombre);
            TipoBarcoLabel.setText(Main_Muelle.muelle.getBarcoLabel());
            
            if (Main_Muelle.muelle.getBarcoLabel().equals("Pasajero")) {
                DatosBarcoArea.setText("DATOS DE BARCO: \n" + Main_Muelle.muelle.getBarcoPasajero().toString() + "\n\nLISTA DE PASAJEROS: \n" + Main_Muelle.muelle.getBarcoPasajero().listarPasajeros());
            } else if (Main_Muelle.muelle.getBarcoLabel().equals("Pesquero")) {
                DatosBarcoArea.setText("DATOS DE BARCO: \n" + Main_Muelle.muelle.getBarcoPesquero().toString());
            }
            
            double total = Main_Muelle.muelle.vaciarBarco(nombre);
            TotalGeneradoLabel.setText("$. " + String.valueOf(total));
        }
        
        
    }//GEN-LAST:event_BotonAgregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaciarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaciarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaciarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaciarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaciarBarco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JTextArea DatosBarcoArea;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField NombreBarcoField;
    private javax.swing.JLabel TipoBarcoLabel;
    private javax.swing.JLabel TotalGeneradoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
